# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38a341bd856ca95d938b1c38d709f65c889d36192fac1df9a616b1a09308dcf534ba7a2b9c304683de236eb8b4a69ac0ec0487d24c1e94eb52395665287a6ed1

test:
  secret_key_base: 02ac45488cb87389ba30cfabcba083fedce7a8d17a1577540f764d7b78ba04ba09c6a94ab9d38dba9caa1949f6ced70dda75069d91e8110b5321aaac96f45d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
